#!/usr/bin/env python3
# -*- encoding: utf-8 -*-

"""
ThinkPad-tool commandline wrapper
"""
import os
import sys
from thinkpad_tool.cmd import commandline_parser

if __name__ == '__main__':
    commandline_parser(sys.argv[1:])
