#!/usr/bin/env python3
# -*- encoding: utf-8 -*-

"""
ThinkPad-tools commandline wrapper
"""
import os
import sys
from thinkpad_tools_assets.cmd import commandline_parser

if __name__ == '__main__':
    commandline_parser(sys.argv[1:])
