#!/usr/bin/env python3
# -*- encoding: utf-8 -*-

"""
ThinkPad-tools commandline wrapper
"""
import sys
from thinkpad_tools_assets.cmd import commandline_parser
import meta

if __name__ == '__main__':
    if len(sys.argv) == 1:
        print(f"{meta.PACKAGE_NAME} v{meta.VERSION}")
    commandline_parser(sys.argv[1:])
